import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lato, Playfair_Display } from 'next/font/google'
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const titleFont = Playfair_Display({
  subsets: ['latin'],
  variable: '--title-font'
})
const normalFont = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ['latin'],
  variable: '--normal-font'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${titleFont.variable} ${normalFont.variable}  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
